### ISSUE TITLE
Have you happened to check if gradio_dmd.py works?

### ISSUE THREAD

**Issue by EYcab** [Zeqiang-Lai/OpenDMD#3]
I have followed your instruction, but it seems your model files in huggingface don't work with your gradio_dmd.py
![1712667450641](https://github.com/Zeqiang-Lai/OpenDMD/assets/11568206/c01fedd3-2cd8-4f12-8292-0362e714a4a1)

**Comment by Zeqiang-Lai** [comment]
It should work, if you have any issue, could you share the error messages so that I can help

**Comment by EYcab** [comment]
![edf3ae1736fa7b3e3874927b9b2af72](https://github.com/Zeqiang-Lai/OpenDMD/assets/11568206/3e33a357-d6a8-4631-a275-c147df4cc85a)
Above is a part of your code and below is the result.
![1712752013277](https://github.com/Zeqiang-Lai/OpenDMD/assets/11568206/3614a96e-6288-4dcb-b797-d6d50cc4061b)

**Comment by EYcab** [comment]
> I have followed your instruction, but it seems your model files in huggingface don't work with your gradio_dmd.py ![1712667450641](https://private-user-images.githubusercontent.com/11568206/320854247-c01fedd3-2cd8-4f12-8292-0362e714a4a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTI0NjksIm5iZiI6MTcxMjc1MjE2OSwicGF0aCI6Ii8xMTU2ODIwNi8zMjA4NTQyNDctYzAxZmVkZDMtMmNkOC00ZjEyLTgyOTItMDM2MmU3MTRhNGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEyMjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMzBjY2I4MjRmNjYzMmUxM2RkNjA5ZjI4OTI1ZmIzMmQ3N2QwOGU3ZDJlMWQ3ZmFmMTg1M2YxY2NkNmVlYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DrFZ8mC8RiIRr0nzxtGus1zW-2phORNwiJDCFwTBb7I)

It suggests that your --model-path file is missing something.

**Comment by yethu** [comment]
@EYcab I was having the same problem but running `sanity_check.py` fixed it. Now, I am facing an entirely new error in the next step.
```
root@machine:/workspace/OpenDMD# python gradio_dmd.py --unet-path '/workspace/dreamshaper-8' --model-path '/workspace/dreamshaper-8-dmd-kl-only-6kstep'
Traceback (most recent call last):
  File "/workspace/OpenDMD/gradio_dmd.py", line 18, in <module>
    pipe = DiffusionPipeline.from_pretrained(args.model_path, unet=unet)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 692, in from_pretrained
    config_dict = cls.load_config(cached_folder)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 374, in load_config
    raise EnvironmentError(
OSError: Error no file named model_index.json found in directory /workspace/dreamshaper-8-dmd-kl-only-6kstep.
```

**Comment by EYcab** [comment]
Well,I have been there before @yethu

**Comment by Pure-Giant-Goliath** [comment]
I tried with swapping unet-path and model-path and it works successfully.
